# Generated by Django 5.2.8 on 2025-12-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0004_remove_staff_department_wardenprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='users.wardenprofile'),
        ),
    ]
