# Generated by Django 5.2.8 on 2025-11-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'Head of Department'), ('warden', 'Warden'), ('dean', 'Principal'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
