# Generated by Django 5.2.8 on 2025-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_parents_name_student_parents_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'HOD'), ('warden', 'Warden'), ('dean', 'Dean'), ('other', 'Other')], max_length=20),
        ),
    ]
