# Generated by Django 5.2.8 on 2025-12-14 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.CreateModel(
            name='WardenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_phone', models.CharField(max_length=15)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warden_profile', to='users.staff')),
            ],
        ),
    ]
