# Generated by Django 5.2.8 on 2025-12-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_branch_staff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
