# Generated by Django 5.2.8 on 2025-12-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'HOD'), ('warden', 'Warden'), ('dean', 'Dean'), ('admin', 'Admin'), ('security_guard', 'Security Guard'), ('other', 'Other')], max_length=20),
        ),
    ]
