# Generated by Django 5.2.8 on 2025-12-12 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('parents_name', models.CharField(max_length=250)),
                ('parents_number', models.CharField(max_length=20)),
                ('attachment', models.FileField(upload_to='media/')),
                ('approvedby_warden', models.BooleanField(default=False)),
                ('approvedby_hod', models.BooleanField(default=False)),
                ('approvedby_teacher', models.BooleanField(default=False)),
                ('final_status', models.CharField(default='Pending', max_length=150)),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('leave_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leave.leaverequest')),
            ],
        ),
    ]
