# Generated by Django 5.2.8 on 2025-12-13 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_leaverequest_student_leaverequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approvedby_hod_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvedby_teacher_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvedby_warden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_leave', to='leave.leaverequest'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(upload_to='leave_attachments/'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
    ]
