# Generated by Django 5.2.8 on 2025-12-14 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leaverequest_rejected_at_leaverequest_rejected_by_and_more'),
        ('users', '0005_remove_student_branch_staff_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Expired', 'Expired'), ('Revoked', 'Revoked')], default='Active', max_length=20)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_gatepasses', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gatepass', to='leave.leaverequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepasses', to='users.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
