# Generated by Django 5.2.8 on 2025-12-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_gatepass_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approvedby_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvedby_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvedby_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvedby_dean_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
