# Generated by Django 5.2.8 on 2025-12-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leaverequest_approvedby_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='code',
            field=models.CharField(db_index=True, default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='final_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Holiday', 'Holiday')], default='Normal', max_length=20),
        ),
    ]
